### 在此文件中，禁用自动补全

InputRoot: test #project
OutputPath: output\test.ini #D:\Users\EC\Saved Games\io.soloev.rshin\__Mod__\rule\Generated.ini
MacroRoot: project/@Macro
RegisterFile: 09. Registery.ini # Registery table will be injected into content of this file (will not change the source file)

# IsRelease: true

Registery:
  - Target: InfantryTypes
    Start: 1
    Source: 
      - NATO\Infantries.ini
      - Soviet\Infantries.ini
      - PRC\Infantries.ini
      - Civilian\Citizens.ini
      - Civilian\Animals.ini
  - Target: VehicleTypes
    Start: 1
    Source:
      - 14. Allied Vehicles.ini
      - 15. Soviet Vehicles.ini
      - 16. P.R.C. Vehicles.ini
      - 17. Civilian Vehicles.ini
      - PRC\21. 陆地载具.ini
      - PRC\22. 海上载具.ini
      - PRC\23. 悬浮机.ini
  - Target: AircraftTypes
    Start: 20
    Source:
      - PRC\31. 喷气机.ini
  - Target: BuildingTypes
    Start: 450
    Source:
      - 18. Allied Buildings.ini
      - 19. Soviet Buildings.ini
      - 20. P.R.C. Buildings.ini
      - 21. Civilian Buildings.ini
      - PRC\41. 生产建筑.ini
      - PRC\42. 防御建筑.ini
      - PRC\43. 其它建筑.ini
  - Target: Projectiles
    Source:
      - 40. 抛射体.ini
      - 抛射体\炮弹.ini
  - Target: Warheads
    Start: 150
    Source:
      - 50. 弹头.ini
  - Target: WeaponTypes
    Source:
      - 60. 盟军武器.ini
      - 61. 苏军武器.ini
      - 63. 平民武器.ini
      - 64. 超武武器.ini
      - 武器\PRC\载具.ini
      - 武器\PRC\步兵.ini
      - 武器\PRC\飞机.ini
      - 武器\PRC\海军.ini
      